### PR TITLE
Project pages and home page abstracts

### PR DESCRIPTION
**Pull request by naummo**
Temporary preview hosted with Jekyll: [http://naumsmogers.me:4000/](http://naumsmogers.me:4000/)
This PR adds project pages, respective homepage blocks to the homepage and menu items. The abstracts were adapted from publications, posters and homepages. Please check the project titles, icons and abstracts.

Note: project pages list publications, presentations and posters, which will need to be updated in the future.

Minor changes include:
- Bigger regular text size;
- Fixed alternating background colors on the main page for the new "Open positions" sections;
- Stretched and centered the dropdown projects menu;
- Minor offset changes for OCD pleasure.

### CODE REVIEW

**Comment by michel-steuwer** [comment]
Also, I like to suggest to use this: http://fontawesome.io/icon/arrows/ for the stencil icon

**Comment by naummo** [comment]
@michel-steuwer For poster pictures, how about arranging them horizontally above the abstract in project pages? Otherwise, if they are arranged vertically in the sidebar, the "Researchers" sections gets pushed far below.

All the other suggestions - done!

**Comment by tremmelg** [comment]
- Michel is listed with his old position in the research directions pages
- If Christophe is listed as supervisor in the research directions pages, shouldn't Michel be as well?
- The title font in the research directions pages is different from the main page.
- I think the CASES abstract would work better for the linear algebra page.
- Is the CGO paper really about linear algebra? If so, shouldn't the talk be there as well?

**Comment by michel-steuwer** [comment]
Yeah, we have a discussion! Thanks, again Naums for doing this.

I have optinions on Toomas points:
 - I don't have a strong opinion if Christophe and I should be listed as "Supervisors" or with the same titles as given in the Team section on the main site. But if we go for the titles from the Team section they should be consistend.
 - I think I might be fine with Arial for the Research Directions titles as It might look a bit too much with the Rennie Mackintosh font we use for the other headings (but maybe it's worthwile a try)
 - I think it's fine to list the CGO paper under the Linear Algebra section and I agree with Toomas that we should have the CGO talk listed there as well

**Comment by michel-steuwer** [comment]
Thaks @naummo for the changes you made already!

Regarding the poster I think they should be in the mange page, not the side bar. Maybe below the abstracts?

**Comment by cdubach** [comment]
Maybe put me as "advisor" for my own student and Michel as collaborator?

**Comment by tremmelg** [comment]
It still says UoE for Michel :)

**Comment by naummo** [comment]
For poster thumbnails, do we want to store them in the **posters** repo to keep everything together or in **lift-project.github.io/images** not to clutter **posters**?

**Comment by naummo** [comment]
All suggestions are now implemented (Bastian's will be a separate PR). Anything else?

**Comment by michel-steuwer** [comment]
Thanks, Naums!

The only bit I found now while browsing through the website is the subtitle on the Sparse Data Parallelism site which is the same as on the Linear Algebra site.
Instead I'd suggest to use "Compositional Compilation for Sparse, Irregular Data Parallelism" as a subtitle here.

**Comment by michel-steuwer** [comment]
I would also prefer to just use the "Lecturer" and "Reader" title for Christophe and me on the individual sites. E.g. for Bastian we are both not his official PhD advisor, but Christophe is for Larisa, ... so what do we write there then? I would just suggest using the "normal" titles and we can clarify on our own websites who we are supersiving or collaborating with. What do you think, @cdubach?

**Comment by michel-steuwer** [comment]
Hey @naummo, I would suggest that you re-rename the "Supervisor" and "Collaborator" titles to the more neutral "Reader" and "Lecturer" and that we than merge this. We can discuss all further changes in separate pull requests.

**Pull request merged**
