### PR TITLE
Integration with Jekyll, Bootstrap menu, profile section on the project page

### PR DESCRIPTION
**Pull request by naummo**
Christophe suggested to use server-side include for things like menu that are supposed to stay the same across all pages. As GitHub supports **Jekyll**, I converted existing pages to its format, which supports  variables and including `html` files.
- CSS/JS inclusions, menu, the title section and copyrights are now the same on all pages
- Title section is defined by variables of the page (see `ml.html` for an example)

"Research Directions" is now a dropdown menu based on **Bootstrap**. Would be nice to add smooth transitions in future. TODO: blurring background behind the dropdown box -- when the list gets bigger, it'll overlap with the title and become partially unreadable.
TODO 2: make the "Research directions" submenu open on hover, and send to the "Research directions" section on click.

Jekyll How-To: http://jekyllbootstrap.com/lessons/jekyll-introduction.html
Installing Jekyll locally to render pages before pushing: https://help.github.com/articles/setting-up-your-github-pages-site-locally-with-jekyll/#step-2-install-jekyll-using-bundler

Oh, and converted tabs to spaces. Because [http://www.bbc.co.uk/news/technology-40302410](http://www.bbc.co.uk/news/technology-40302410).

### CODE REVIEW

**Comment by bastianhagedorn** [comment]
Hi, since I have no clue about web development whatsoever, my thoughts about the changes and my approval as reviewer would be useless for this pull-request ;)

**Comment by naummo** [comment]
For those inside the Informatics Forum network, I've launched a Jekyll engine to preview the pull request, accessible via [http://artemisa:4000/](http://artemisa:4000/).

**Comment by bastianhagedorn** [comment]
This is helpful :) If you now click at `Research Directions` only the menu opens. I'd expect it to open when hovering over it and with a click I'd expect to be directed to the overview on the main page if that makes sense

**Comment by naummo** [comment]
Good point. I thought I'd leave it for later, but I guess it is too confusing to leave it like that. Will do.

**Comment by naummo** [comment]
Implemented all suggestions proposed at today's meeting and by Bastian.
Ready for approval ;)

**Pull request merged**
